# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @resurrect-save-cwd 'on'
set-option -g default-shell /usr/bin/zsh
set-environment -g PATH "$HOME/bin:$PATH"

bind ¸ source-file ~/.tmux.conf \; display-message "Config reloaded"

set -g base-index 1
setw -g pane-base-index 1
setw -g mode-keys vi

bind -n M-h select-pane -L
bind -n M-j select-pane -R
bind -n M-k select-pane -U
bind -n M-l select-pane -D

set-option -g allow-rename off

set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

set -g mouse on

set -g status-right-style 'fg=white'
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50

set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=red'
set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -g status-style 'bg=#5549AE fg=#fff0f5'


bind C-c run "tmux save-buffer - | xclip -i -sel clip"
bind C-v run "tmux set-buffer $(xclip -o -sel clip); tmux paste-buffer"

bind-key C-b copy-mode

bind -T copy-mode-vi C-k if-shell -F "#{==:#{pane_current_command},nvim}" "send-keys C-k" "send-keys -X page-up"
bind -T copy-mode-vi C-j if-shell -F "#{==:#{pane_current_command},nvim}" "send-keys C-j" "send-keys -X page-down"

bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"

bind -T copy-mode-vi v send-keys -X begin-selection

unbind -T copy-mode-vi c
bind -T copy-mode-vi C-x send-keys -X clear-screen

bind-key s run-shell "$HOME/scripts/tmux-save.sh"
bind-key r display-popup -E "$HOME/scripts/tmux-restore.sh"

bind-key m display-popup -E -w 80% -h 70% "$HOME/scripts/fman.sh"

bind-key a display-popup -E -d "#{pane_current_path}" "$HOME/scripts/fzf-nvim.sh ."
bind-key h display-popup -E "$HOME/scripts/fzf-nvim $HOME"

bind-key d display-popup -E "$HOME/scripts/fzf-dir.sh $HOME"

bind-key z display-popup -E "$HOME/scripts/zoxide-fzf.sh"

bind š confirm-before -p "Kill tmux server? (y/n)" "kill-server"

run '~/.tmux/plugins/tpm/tpm'
